#! /bin/sh

sxhkd &
polybar -r main &
# feh -bg-fill ~/Images/openonedarksourcerer.png &
~/script/xmodmap.sh &

bspc monitor -d I II III IV V VI

# overlap
bspc config border_width          6
bspc config window_gap            25

bspc config top_padding           30

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config focused_border_color  "#5c6370"
bspc config normal_border_color   "#4b5263"

bspc config focus_follows_pointer true
